<?php 
/**
 * This file is part of the TEKKL core package
 *
 * (c) Alexander Bachmann <email.bachmann@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Tekkl\Bundle\UserBundle\Repository;

use Tekkl\Bundle\UserBundle\Entity\UserToken;

/**
 * UserTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTokenRepository extends \Doctrine\ORM\EntityRepository
{
	public function deleteExpiredTokens(){
		$em = $this->getEntityManager();
		$date = new \DateTime();

		$qb = $em->createQueryBuilder();
		$qb->delete('TekklUserBundle:UserToken', 't');
		$qb->where('t.expires < :date');
		$qb->setParameter('date', $date);

		$qb->getQuery()->execute();
	}
}
