services:
    tekkl_user.listener.authentication_success.cookie:
        class: Tekkl\Bundle\UserBundle\EventListener\Authentication\CookieSetter
        arguments: ['%tekkl_user.jwt.cookie.name%', '%tekkl_user.jwt.cookie.ttl%']
        tags:
            - { name: kernel.event_listener, event: !php/const:Lexik\Bundle\JWTAuthenticationBundle\Events::AUTHENTICATION_SUCCESS, method: onAuthenticationSuccess }

    tekkl_user.listener.authentication_failure.cookie:
        class: Tekkl\Bundle\UserBundle\EventListener\Authentication\CookieSetter
        arguments: ['%tekkl_user.jwt.cookie.name%', '%tekkl_user.jwt.cookie.ttl%']
        tags:
            - { name: kernel.event_listener, event: !php/const:Lexik\Bundle\JWTAuthenticationBundle\Events::AUTHENTICATION_FAILURE, method: onAuthenticationFailure }

    tekkl_user.listener.authentication_success.authorization_header:
        class: Tekkl\Bundle\UserBundle\EventListener\Authentication\AuthorizationHeaderSetter
        arguments: ['%tekkl_user.jwt.authorization_header.name%', '%tekkl_user.jwt.authorization_header.prefix%']
        tags:
            - { name: kernel.event_listener, event: !php/const:Lexik\Bundle\JWTAuthenticationBundle\Events::AUTHENTICATION_SUCCESS, method: onAuthenticationSuccess }

    tekkl_user.listener.authentication_success.body_token_remover:
        class: Tekkl\Bundle\UserBundle\EventListener\Authentication\BodyTokenRemover
        tags:
            - { name: kernel.event_listener, event: !php/const:Lexik\Bundle\JWTAuthenticationBundle\Events::AUTHENTICATION_SUCCESS, method: onAuthenticationSuccess, priority: -255 }

    tekkl_user.listener.authentication_success.body_user_setter:
        class: Tekkl\Bundle\UserBundle\EventListener\Authentication\BodyUserSetter
        tags:
            - { name: kernel.event_listener, event: !php/const:Lexik\Bundle\JWTAuthenticationBundle\Events::AUTHENTICATION_SUCCESS, method: onAuthenticationSuccess }

    tekkl_user.listener.authentication_failure.reauthentication:
        class: Tekkl\Bundle\UserBundle\EventListener\Authentication\RefreshTokenReauthentication
        arguments: ['@request_stack', '@gesdinet.jwtrefreshtoken']
        tags:
            - { name: kernel.event_listener, event: !php/const:Lexik\Bundle\JWTAuthenticationBundle\Events::AUTHENTICATION_FAILURE, method: reauthenticate }

    tekkl_user.listener.registration_failure.form_exception:
        class: Tekkl\Bundle\UserBundle\EventListener\Registration\RegistrationFailureFormException
        tags:
            - { name: kernel.event_listener, event: !php/const:FOS\UserBundle\FOSUserEvents::REGISTRATION_FAILURE, method: onRegistrationFailure }

    tekkl_user.listener.registration_success.jwt_authentication:
        class: Tekkl\Bundle\UserBundle\EventListener\Registration\JwtAuthentication
        arguments: ['@lexik_jwt_authentication.handler.authentication_success', '@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: !php/const:FOS\UserBundle\FOSUserEvents::REGISTRATION_COMPLETED, method: onRegistrationCompleted, priority: -255 }
